{
 "title": "powerstore exporter from prometheus dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "IP", "query": { "query": "label_values(IP)" } },
   {
    "name": "Appliance",
    "query": {
     "query": "label_values(powerstore_appliance{},appliance_id)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(powerstore_cluster{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_appliance{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_perf_io_workload_cpu_utilization{IP=\"$IP\"}[1h])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_efficiency_ratio{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_logical_provisioned{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_physical_used{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_physical_total{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_logical_used{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_latency{IP=\"$IP\"} * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_total_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_total_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "[$Appliance] FcPort latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_avg_latency{IP=\"$IP\",appliance_id=\"$Appliance\"} * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] FcPort IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_avg_total_iops{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] FcPort Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_avg_total_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] FCPort Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_avg_prim_seq_prot_err_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_loss_of_sync_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_loss_of_signal_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_link_failure_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_invalid_tx_word_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_invalid_crc_count_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_dumped_frames_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_fc_port_is_link_up{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] EthPort Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "powerstore_metricEthPort_avg_bytes_rx_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_avg_bytes_tx_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_avg_pkt_rx_crc_error_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_avg_pkt_rx_no_buffer_error_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_avg_pkt_rx_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_tx_error_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_tx_ps{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_eth_port_is_link_up{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "[$Appliance] Volume Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_latency{IP=\"$IP\", appliance_id=\"$Appliance\"} * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_read_iops{IP=\"$IP\",appliance_id=\"$Appliance\"} + powerstore_metricVolume_avg_write_iops{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance]  Volume Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_write_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\"} + powerstore_metricVolume_avg_read_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "powerstore_volume_size{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_state{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_logical_used{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_logical_used{IP=\"$IP\",appliance_id=\"$Appliance\"}/powerstore_volume_size{IP=\"$IP\",appliance_id=\"$Appliance\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "[$Appliance] Volume Group  latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricVg_avg_latency{IP=\"$IP\",appliance_id=\"$Appliance\"} * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Group  IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricVg_avg_total_iops{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Group Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricVg_avg_total_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Group Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "powerstore_volumegroup_logical_provisioned{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volumegroup_logical_used{IP=\"$IP\",appliance_id=\"$Appliance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volumegroup_logical_used{IP=\"$IP\",appliance_id=\"$Appliance\"}/powerstore_volumegroup_logical_provisioned{IP=\"$IP\",appliance_id=\"$Appliance\"} *100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "[$Appliance] Drive Information",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "last_over_time(powerstore_hardware_Drive_state{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_hardware_drive_size{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_wear_metrics_by_drive{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Node  Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 68 },
   "targets": [
    {
     "expr": "last_over_time(powerstore_hardware_node_state{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Power Supply  Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 68 },
   "targets": [
    {
     "expr": "last_over_time(powerstore_hardware_Power_Supply_state{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Fan Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 73 },
   "targets": [
    {
     "expr": "last_over_time(powerstore_hardware_Fan_state{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Battery Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 75 },
   "targets": [
    {
     "expr": "last_over_time(powerstore_hardware_Battery_state{IP=\"$IP\",appliance_id=\"$Appliance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}